INSERT INTO DEVICE VALUES (1, 'ROVER', 'MOON', 'CAMERA', 100, false,null); 
INSERT INTO DEVICE VALUES (2, 'SATELLITE', 'EARTH', 'WALDO', 80, false, null); 
INSERT INTO DEVICE VALUES (3, 'VOYAGER', 'MARS', 'SENSORS', 30, false, null);
INSERT INTO DEVICE VALUES (4, 'GALILLEO', 'MOON', 'CAMERA', 65, false, null);
INSERT INTO DEVICE VALUES (5, 'PATHFINDER', 'SATURN', 'INFRARED', 45, false, null);